### ISSUE TITLE
osgUtil dependency missing

### ISSUE THREAD

**Issue by mmaurus** [rock-gui/osgdb_bobj#1]
osgdb_bobj does not compile under msys2 due to linkerError:

    CMakeFiles/osgdb_bobj.dir/objects.a(ReaderWriterBOBJ.cpp.obj):ReaderWriterBOBJ.cpp:(.text+0x1232): undefined reference to `__imp__ZTVN7osgUtil9OptimizerE'
    CMakeFiles/osgdb_bobj.dir/objects.a(ReaderWriterBOBJ.cpp.obj):ReaderWriterBOBJ.cpp:(.text+0x129e): undefined reference to `__imp__ZN7osgUtil9Optimizer8optimizeEPN3osg4NodeE'

FIX: add "openscenegraph-osgUtil" to DEPS_PKGCONFIG in CMakeLists.txt

**Comment by planthaber** [comment]
added it
